---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(Seurat)
library(patchwork)
library(Matrix)
library(ggplot2)
library(tibble)
library(cowplot)
library(purrr)
library(SeuratDisk)
library(RColorBrewer)
```

```{r}
wdir <- '~/Jansky/ms_phate/msphate_jansky/msPHATE-Seurat/'
data_name <- 'seurat/adrenal_dataulla_Seurat.RDS.gz'
data <- readRDS(paste(wdir, data_name, sep = ''))
```

#### Standard workflow
```{r}
write.table(GetAssayData(data, 'scale.data'), file = paste(wdir, 'counts.csv', sep = ''), sep = ',', row.names = FALSE, col.names = FALSE)
write.table(colnames(GetAssayData(data, 'scale.data')), file = paste(wdir, 'cell_names.txt', sep = ''), sep = ',', row.names = FALSE, col.names = FALSE)
write.table(rownames(GetAssayData(data, 'scale.data')), file = paste(wdir, 'gene_names.txt', sep = ''), sep = ',', row.names = FALSE, col.names = FALSE)
```

```{python}
### USAGE ###
# Export counts.csv. gene_names.txt and cell.names.txt from R
# Now you can load in data by restarting
# Find msPHATE clusters at different levels with clus
### USAGE ###

import multiscale_phate as mp
import numpy as np
import pandas as pd
import scprep
import os

wdir = '~/Jansky/ms_phate/msphate_jansky/msPHATE-Seurat'
npca = 20
gran = 0.1

wdir = os.path.expanduser(wdir)
gene_path = os.path.join(wdir, 'gene_names.txt')
cell_path = os.path.join(wdir, 'cell_names.txt')

print('Loading scaled data...')
data_path = os.path.join(wdir, 'counts.csv')
data = scprep.io.load_csv(data_path, cell_axis='column',
                        gene_names=gene_path,
                        cell_names=cell_path)

mp_op = mp.Multiscale_PHATE(n_pca=npca, granularity=gran, random_state=0)
levels = mp_op.fit(data)

def clus(clustering_level, vis_level = 0):
    clus_level = clustering_level
    print('Generating embedding and assigning clusters...')
    embedding, clusters, sizes = mp_op.transform(visualization_level = levels[vis_level],
                                                               cluster_level = levels[-1*clus_level])

    print('Exporting embedding and clusters...')
    msPHATE_embedding = pd.DataFrame(embedding,
                          index = pd.read_csv(cell_path, header=None).iloc[:, 0].to_list())
    msPHATE_embedding.to_csv('msPHATE_embedding.csv', header=False)
    msPHATE_clusters = pd.DataFrame(clusters)
    msPHATE_clusters.to_csv('msPHATE_clusters.csv', header=False, index=False)

    print('\n')
    print(data)
    print('\n')
    print(levels)
    print('\n')
    print(embedding)
    print('\n')
    print(set(clusters))
    print ('\n')
    print(' Clustering level ' + str(clus_level))
    print('\n')
    print('Done')
```

```{r}
msPHATE_embedding <- read.csv(paste(wdir, 'msPHATE_embedding.csv', sep = ''), header=FALSE, row.names = 1, col.names = c('', 'msPHATE_1', 'msPHATE_2'))
msPHATE_embedding <- as.matrix(msPHATE_embedding)
data[['msphate']] <- CreateDimReducObject(embeddings = msPHATE_embedding, key = 'msPHATE_')
```

```{r}
msPHATE_clusters <- as.matrix(read.csv(paste(wdir, 'msPHATE_clusters.csv', sep = ''), header=FALSE))
msPHATE_clusters <- factor(msPHATE_clusters)
data$msphate_clusters <- msPHATE_clusters
```

```{r}
DimPlot(data, reduction = 'msphate', group.by = 'msphate_clusters', pt.size = 1)
```

#### Extracting all genes
```{r}
data_all <- data
data_all <- NormalizeData(data_all)
data_all <- ScaleData(object = data_all, features = rownames(data_all@assays$RNA@counts))
Misc(data, 'scale.data_all') <- GetAssayData(data_all, 'scale.data')
data@misc$scale.data_all[1:5, 1:5]
rm(data_all)

write.table(data@misc$scale.data_all, file = paste(wdir, 'counts.csv', sep = ''), sep = ',', row.names = FALSE, col.names = FALSE)
write.table(colnames(data@misc$scale.data_all), file = paste(wdir, 'cell_names.txt', sep = ''), sep = ',', row.names = FALSE, col.names = FALSE)
write.table(rownames(data@misc$scale.data_all), file = paste(wdir, 'gene_names.txt', sep = ''), sep = ',', row.names = FALSE, col.names = FALSE)
# Standard workflow from msphate.py onwards
# Store reduction and clusters under different names in Seurat object so as to not overwrite previous work!
```

```{r}
# Run msphate.py first!
msPHATE_embedding <- read.csv(paste(wdir, 'msPHATE_embedding.csv', sep = ''), header=FALSE, row.names = 1, col.names = c('', 'msPHATE_1', 'msPHATE_2'))
msPHATE_embedding <- as.matrix(msPHATE_embedding)
data[['msphate_all']] <- CreateDimReducObject(embeddings = msPHATE_embedding, key = 'msPHATE_')
```

```{r}
msPHATE_clusters <- as.matrix(read.csv(paste(wdir, 'msPHATE_clusters.csv', sep = ''), header=FALSE))
msPHATE_clusters <- factor(msPHATE_clusters)
data$msphate_clusters_all <- msPHATE_clusters
```

```{r}
data[['pca_all']] <- CreateDimReducObject(embeddings = Embeddings(data[['pca']]), key = 'PC_')
data@reductions$pca <- NULL

umap_tsne_all <- data
data$jansky_idents <- Idents(data)
all_genes <- rownames(GetAssayData(umap_tsne_all, 'scale.data'))
umap_tsne_all <- ScaleData(umap_tsne_all, features = all_genes)
umap_tsne_all <- RunPCA(object = umap_tsne_all, features = all_genes, reduction.name = 'pca_all')
umap_tsne_all <- FindNeighbors(object = umap_tsne_all, reduction = 'pca_all')
umap_tsne_all <- FindClusters(object = umap_tsne_all, resolution = 1.2)
umap_tsne_all <- RunUMAP(object = umap_tsne_all, features = all_genes)
umap_tsne_all <- RunTSNE(object = umap_tsne_all, features = all_genes)
data <- RunTSNE(object = data, features = VariableFeatures(data), reduction = 'pca_all')


data[['umap_all']] <- CreateDimReducObject(embeddings = Embeddings(umap_tsne_all[['umap']]), key = 'UMAP_')
data[['tsne_all']] <- CreateDimReducObject(embeddings = Embeddings(umap_tsne_all[['tsne']]), key = 'UMAP_')
data$seurat_clusters_all <- umap_tsne_all$seurat_clusters
rm(umap_tsne_all)
```

```{r}
DimPlot(data, reduction = 'msphate', group.by = 'msphate_clusters', pt.size = 1)
DimPlot(data, reduction = 'msphate_all', group.by = 'msphate_clusters_all', pt.size = 1)

DimPlot(data, reduction = 'umap', group.by = 'seurat_clusters', pt.size = 1)
DimPlot(data, reduction = 'umap_all', group.by = 'seurat_clusters_all', pt.size = 1)

DimPlot(data, reduction = 'tsne', group.by = 'seurat_clusters', pt.size = 1)
DimPlot(data, reduction = 'tsne_all', group.by = 'seurat_clusters_all', pt.size = 1)
```

#### Using unscaled data
```{r}
data_unscaled <- data
data_unscaled <- NormalizeData(data_unscaled)
data_unscaled <- ScaleData(data_unscaled, do.scale = FALSE)
Misc(data, 'scale.data_unscaled') <- GetAssayData(data_unscaled, 'scale.data')
data@misc$scale.data_unscaled[1:5, 1:5]
rm(data_unscaled)
```

```{r}
write.table(data@misc$scale.data_unscaled, file = paste(wdir, 'counts.csv', sep = ''), sep = ',', row.names = FALSE, col.names = FALSE)
write.table(colnames(data@misc$scale.data_unscaled), file = paste(wdir, 'cell_names.txt', sep = ''), sep = ',', row.names = FALSE, col.names = FALSE)
write.table(rownames(data@misc$scale.data_unscaled), file = paste(wdir, 'gene_names.txt', sep = ''), sep = ',', row.names = FALSE, col.names = FALSE)
# Run msphate.py
```

```{r}
# Run msphate.py first!
msPHATE_embedding <- read.csv(paste(wdir, 'msPHATE_embedding.csv', sep = ''), header=FALSE, row.names = 1, col.names = c('', 'msPHATE_1', 'msPHATE_2'))
msPHATE_embedding <- as.matrix(msPHATE_embedding)
data[['msphate_unscaled']] <- CreateDimReducObject(embeddings = msPHATE_embedding, key = 'msPHATE_')
# Only run once - embedding constant for different clustering levels
```

```{r}
msPHATE_clusters <- as.matrix(read.csv(paste(wdir, 'msPHATE_clusters.csv', sep = ''), header=FALSE))
msPHATE_clusters <- factor(msPHATE_clusters)
data$msphate_clusters_lvl3_unscaled <- msPHATE_clusters
```

```{r}
umap_tsne_unscaled <- data
umap_tsne_unscaled <- RunPCA(object = umap_tsne_unscaled, reduction.name = 'pca_unscaled')
umap_tsne_unscaled <- FindNeighbors(object = umap_tsne_unscaled, reduction = 'pca_unscaled')
umap_tsne_unscaled <- FindClusters(object = umap_tsne_unscaled, resolution = 1.2)
umap_tsne_unscaled <- RunUMAP(object = umap_tsne_unscaled, features = VariableFeatures(umap_tsne_unscaled))
umap_tsne_unscaled <- RunTSNE(object = umap_tsne_unscaled, features = VariableFeatures(umap_tsne_unscaled), reduction = 'pca_unscaled')

data[['umap_unscaled']] <- CreateDimReducObject(embeddings = Embeddings(umap_tsne_unscaled[['umap']]), key = 'UMAP_')
data[['tsne_unscaled']] <- CreateDimReducObject(embeddings = Embeddings(umap_tsne_unscaled[['tsne']]), key = 'UMAP_')
data$seurat_clusters_unscaled <- umap_tsne_all$seurat_clusters_unscaled
rm(umap_tsne_unscaled)
```

```{r}
DimPlot(data, reduction = 'msphate', group.by = 'msphate_clusters', pt.size = 1)
DimPlot(data, reduction = 'msphate_unscaled', group.by = 'msphate_clusters_unscaled', pt.size = 1)

DimPlot(data, reduction = 'umap', group.by = 'seurat_clusters', pt.size = 1)
DimPlot(data, reduction = 'umap_unscaled', group.by = 'seurat_clusters_unscaled', pt.size = 1)

DimPlot(data, reduction = 'tsne', group.by = 'seurat_clusters', pt.size = 1)
DimPlot(data, reduction = 'tsne_unscaled', group.by = 'seurat_clusters_unscaled', pt.size = 1)
```

#### Subsetting
```{r}
data_subset <- subset(data, subset = msphate_clusters %in% c('0', '1')) # Or by any other variable
# Then treat as data
```
